StudyAssistant/Models/Administrator.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StudyAssistant.Models
{
    public class Administrator
    {
        public int Id { get; set; }

        [StringLength(60,ErrorMessage ="Digite menos caracteres!")]
        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Name { get; set; }

        [EmailAddress(ErrorMessage = "Digite um email valido!")]
        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Email { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Password { get; set; }
    }
}

StudyAssistant/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StudyAssistant.Models
{
    public class Answer
    {
        public int Id { get; set; }

        [StringLength(1000, ErrorMessage = "Digite menos caracteres!")]
        [Required(ErrorMessage ="Campo obrigatório!")]
        public string Description { get; set; }

        public int QuestionId { get; set; }
    }
}

StudyAssistant/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StudyAssistant.Models
{
    public class Question
    {
        public int Id { get; set; }

        [StringLength(1000, ErrorMessage = "Digite menos caracteres!")]
        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Description { get; set; }
        public int RightAnswerId { get; set; }
        public int TypeOfQuestionId { get; set; }
        public ICollection<Answer> Answers { get; set; }
    }
}

StudyAssistant/Models/TypeOfQuestion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StudyAssistant.Models
{
    public class TypeOfQuestion
    {
        public int Id { get; set; }
        [StringLength(60, ErrorMessage = "Digite menos caracteres!")]
        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Name { get; set; }
    }
}

StudyAssistant/Controllers/AdministratorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudyAssistant.Models;
using StudyAssistant.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace StudyAssistant.Controllers
{
    public class AdministratorsController : Controller
    {

        private readonly SAContexto _Context;

        public AdministratorsController(SAContexto context)
        {
            _Context = context;
        }

        [HttpGet]
        public IActionResult Login()
        {
            ViewBag.Error = "";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([Bind("Email,Password")] Administrator administrator)
        {
            if (!ModelState.IsValid)
            {
                var objAdm = await _Context.Administrators.FirstOrDefaultAsync(adm => adm.Email == administrator.Email && adm.Password == administrator.Password);

                if (objAdm == null)
                {
                    ViewBag.Error = "Email e/ou Senha inválidos!";
                    return View();
                }
                else
                {
                    HttpContext.Session.SetString("Name", objAdm.Name);
                    HttpContext.Session.SetInt32("Id", objAdm.Id);

                    return RedirectToAction("Management");
                }

            }
            
            return View(administrator);
        }

        [HttpGet]
        public IActionResult Management()
        {
            if (string.IsNullOrWhiteSpace(HttpContext.Session.GetString("Name")))
            {
                return RedirectToAction("Login");
            }

            ViewBag.Name = HttpContext.Session.GetString("Name");
            ViewBag.Id = HttpContext.Session.GetInt32("Id");

            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            ViewBag.Error = "";
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Register([Bind("Name","Email","Password")] Administrator administrator)
        {
            if (!ModelState.IsValid)
            {
                return View(administrator);
            }

            var objAdm = await _Context.Administrators.FirstOrDefaultAsync(adm => adm.Email == administrator.Email);

            if (objAdm == null)
            {
                _Context.Add(administrator);
                _Context.SaveChanges();
                return RedirectToAction("Login");
            }
            else
            {
                ViewBag.Error = "Email já cadastrado!";
                return View(administrator);
            }
            
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }


    }
}

StudyAssistant/Views/Administrators/Login.cshtml
@model StudyAssistant.Models.Administrator

@{
    ViewData["Title"] = "Login";
}


    <form class="form formL" asp-controller="Administrators" asp-action="Login">
        <h3 class="text-center">Efetuar Login</h3>
        
        @if (ViewBag.Error != "")
        {
            <span class="text-danger">@ViewBag.Error</span>
        }
    
        <div class="form-group">
            <label label-for="Name">Email:</label>
            <input asp-for="Email" type="email" class="form-control" placeholder="email" autofocus="" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label label-for="Name">Senha:</label>
            <input asp-for="Password" type="password" class="form-control" placeholder="senha" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>

        <br />
        <div class="form-group">
            <div class="btn-group btn-block">
                <a asp-controller="Questions" asp-action="Index" class="btn btn-secondary">Voltar</a> &nbsp; &nbsp;
                <button type="submit" class="btn orangeB">Entrar</button>
            </div>
        </div>
    </form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudyAssistant/Views/Administrators/Management.cshtml
@{
    ViewData["Title"] = "Gerenciar";
}

<h2>@ViewBag.Id</h2>
<br />
<h2>@ViewBag.Name</h2>

StudyAssistant/Views/Administrators/Register.cshtml
@model StudyAssistant.Models.Administrator

@{
    ViewData["Title"] = "Registrar-se";
}


<form class="form formL" asp-controller="Administrators" asp-action="Register">
    <h3 class="text-center">Registrar-se</h3>


    @if (ViewBag.Error != "")
    {
        <span class="text-danger">@ViewBag.Error</span>
    }


    <div class="form-group">
        <label label-for="Name">Nome:</label>
        <input asp-for="Name" type="text" class="form-control" placeholder="nome" autofocus="" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label label-for="Email">Email:</label>
        <input asp-for="Email" type="email" class="form-control" placeholder="email" autofocus="" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label label-for="Name">Senha:</label>
        <input asp-for="Password" type="password" class="form-control" placeholder="senha" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <br />
    <div class="btn-group btn-block">
        <a asp-controller="Questions" asp-action="Index" class="btn btn-secondary">Voltar</a> &nbsp; &nbsp;
        <button type="submit" class="btn orangeB">Salvar</button>
    </div>

</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudyAssistant/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="~/css/Style.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark" id="grafite">
        <a class="navbar-brand" asp-action="Index" asp-controller="Questions">
            <img src="~/images/LogoStudy2.png" alt="Logo StudyAssistant" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSite">

            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSite">
            <ul class="navbar-nav ml-auto">

                @{
                    var name = Context.Session.GetString("Name");

                    if (string.IsNullOrWhiteSpace(name))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Administrators" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Administrators" asp-action="Register">Registrar-se</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <span class="nav-link">Bem-vindo, @name </span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Questions" asp-action="Index">Inicio </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Administrators" asp-action="Logout">Sair</a>
                        </li>
                    }
                }

            </ul>
        </div>
    </nav>

    <div class="container p-5">

        <div>
            @RenderBody()
        </div>
    </div>

    <footer class="rodape navbar-dark">
        Fepe Marte &copy; @DateTime.Now.Year
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>